# Generated by Django 5.1.3 on 2024-11-11 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('link', 'Link'), ('arquivo', 'Arquivo')], max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='materiais/')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='aulas.aula')),
            ],
        ),
    ]
